---
- name: Recreate wordpress stack
  ansible.builtin.command:
    cmd: podman-compose up -d --force-recreate
    chdir: "{{ wordpress_data_dir }}"
  changed_when: true
  become: true
  become_user: "{{ wordpress_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[wordpress_user][1] }}"

- name: Reload caddy
  containers.podman.podman_container_exec:
    name: "{{ wordpress_caddy_container }}"
    command: caddy reload --config /etc/caddy/Caddyfile
  failed_when: false
  become: true
  become_user: "{{ wordpress_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[wordpress_user][1] }}"
