---
- name: Recreate dashy stack
  ansible.builtin.command:
    cmd: podman-compose up -d --force-recreate
    chdir: "{{ dashy_data_dir }}"
  changed_when: true
  become: true
  become_user: "{{ dashy_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[dashy_user][1] }}"
