---
- name: Recreate pterodactyl stack
  ansible.builtin.command:
    cmd: podman-compose up -d --force-recreate
    chdir: "{{ pterodactyl_panel_data_dir }}"
  changed_when: true
  become: true
  become_user: "{{ pterodactyl_panel_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[pterodactyl_panel_user][1] }}"

- name: Reload caddy
  containers.podman.podman_container_exec:
    name: "{{ pterodactyl_panel_caddy_container }}"
    command: caddy reload --config /etc/caddy/Caddyfile
  failed_when: false
  become: true
  become_user: "{{ pterodactyl_panel_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[pterodactyl_panel_user][1] }}"
