---
- name: Recreate jellyfin stack
  ansible.builtin.command:
    cmd: podman-compose up -d --force-recreate
    chdir: "{{ jellyfin_data_dir }}"
  changed_when: true
  become: true
  become_user: "{{ jellyfin_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[jellyfin_user][1] }}"
