---
- name: Recreate caddy stack
  ansible.builtin.command:
    cmd: docker compose up -d --force-recreate
    chdir: "{{ caddy_data_dir }}"
  changed_when: true

- name: Reload caddy
  community.docker.docker_container_exec:
    container: "{{ caddy_container }}"
    command: caddy reload --config /etc/caddy/Caddyfile
  failed_when: false
